-- MySQL Script generated by MySQL Workbench
-- Mon Aug  6 18:32:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bamazon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bamazon` ;

-- -----------------------------------------------------
-- Schema bamazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bamazon` DEFAULT CHARACTER SET latin1 ;
USE `bamazon` ;

-- -----------------------------------------------------
-- Table `bamazon`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bamazon`.`products` ;

CREATE TABLE IF NOT EXISTS `bamazon`.`products` (
  `item_id` INT(11) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `department_name` VARCHAR(45) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `stock_quantity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
